mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                publish: [ '*' ]
                subscribe: [ '*']
                algorithm: 'HS256'
                provider: Unmainsys\HealthKick\Service\MyTokenProvider
