version: '3.8'

services:
    php-fpm:
        container_name: hk-php-fpm
        build:
            context: php-fpm
        environment:
            - XDEBUG_SESSION=PHPSTORM
            - PHP_IDE_CONFIG=${XDEBUG_PHP_IDE_CONFIG}
        volumes:
            - ../:/var/www
            - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        depends_on:
            - mysql
            - mailcatcher
        ports:
            - '${APPLICATION_IP}:9000:9000'

    nginx:
        container_name: hk-nginx
        hostname: hk.nginx
        build:
            context: nginx
        volumes:
            - ../:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/logs:/var/log
        depends_on:
            - php-fpm
        ports:
            - '${APPLICATION_IP}:80:80'
            - '${APPLICATION_IP}:443:443'

    mysql:
        container_name: hk-mysql
        hostname: hk.mysql
        image: mysql:latest
        platform: ${OS_PLATFORM}
        restart: always
        ports:
            - '${APPLICATION_IP}:3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql/etc/my.cnf:/etc/my.cnf
        entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']


    mailcatcher:
        container_name: hk-mailcatcher
        hostname: hk.mailcatcher
        image: schickling/mailcatcher
        platform: ${OS_PLATFORM}
        restart: always
        ports:
            - '${APPLICATION_IP}:1025:1025'
            - '${APPLICATION_IP}:1080:1080'

    mercure:
        container_name: hk-mercure
        hostname: hk.mercure
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            # Uncomment the following line to disable HTTPS
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
            MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY}
        # Uncomment the following line to enable the development mode
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        ports:
            - '81:80'
            - '444:443'
        volumes:
            - mercure_data:/data
            - mercure_config:/config

volumes:
    mysql-data:
    mercure_data:
    mercure_config:
